spring:
  datasource:
    url: jdbc:mysql://localhost:3306/summerplan_manager?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  
  flyway:
    clean-disabled: true

logging:
  level:
    com.summerplan: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

jwt:
  secret: ${JWT_SECRET:summerplan-manager-secret-key-2024}
  expiration: ${JWT_EXPIRATION:86400000} 